modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "messaging"
version = "${version}"
displayName = "Messaging"
authors = "limbang"
description = '''
消息转发：使用 WebSocket 协议，转发玩家消息。
'''
#logoFile = ""

[[dependencies.messaging]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.messaging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.messaging]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"