modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "messaging"
version = "${version}"
displayName = "Messaging"
authors = "limbang"
description = '''
消息转发：使用 WebSocket 协议，转发玩家消息。
'''
#logoFile = ""

[[dependencies.messaging]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.messaging]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.messaging]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"